# Generated by Django 3.2 on 2022-11-17 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
