# Generated by Django 3.2 on 2022-11-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_paper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paper',
        ),
    ]
