# Generated by Django 3.2 on 2022-11-17 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract_thai', models.TextField()),
                ('abstract_eng', models.TextField()),
                ('link_paper', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=150)),
                ('upload_files', models.FileField(blank=True, null=True, upload_to='file')),
                ('date_paper', models.DateField()),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher')),
            ],
        ),
    ]
