# Generated by Django 3.2 on 2022-11-18 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_paper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paper',
        ),
    ]
