# Generated by Django 3.2 on 2022-11-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_teacher_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='link_paper',
            field=models.URLField(),
        ),
    ]
