# Generated by Django 3.2 on 2022-11-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20221118_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='title',
            new_name='title_th',
        ),
        migrations.AddField(
            model_name='paper',
            name='title_eg',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
