# Generated by Django 3.2 on 2022-11-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_teacher_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='title_eg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
