# Generated by Django 3.2 on 2022-11-18 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_paper_title_eg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='title_th',
            new_name='title',
        ),
    ]
