# Generated by Django 3.2 on 2022-11-18 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_title_th_paper_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='title',
            new_name='title_th',
        ),
    ]
