# Generated by Django 3.2 on 2022-11-18 15:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_title_paper_title_th'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geobase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
