# Generated by Django 3.2 on 2022-11-27 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_geobase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Geobase',
        ),
    ]
